### ISSUE TITLE
How to install locally?

### ISSUE THREAD

**Issue by corinloch** [Amritanshu312/Taro#1]
Can you give instructions? Thanks!

**Comment by corinloch** [comment]
Also what's the variable needed for env? Thanks!

**Comment by Amritanshu312** [comment]
> Also what's the variable needed for env? Thanks!

I will add a .env.example file soon, which will include all the necessary environment variables. This way, you'll have a clear reference for what needs to be configured on your end.

**Comment by Amritanshu312** [comment]
> Can you give instructions? Thanks!

Now I have Added the instruction to run it locally. You can check it out
